#pragma once
typedef enum
{
	EXC_WRONG_NUMOFFILE,
	EXC_NO_WINDOW_SHOT,
	EXC_OTHER_EXCEPTION,
	EXC_SPEED_OUT_OF_RANGE,
	EXC_SENSITIVITY_OUT_OF_RANGE,
	EXC_SCROLL_SENSITIVITY_OUT_OF_RANGE
}MyException;