#pragma once
typedef enum
{
	EXC_WRONG_NUMOFFILE,
	EXC_NO_WINDOW_SHOT,
	EXC_OTHER_EXCEPTION,
	EXC_SPEED_OUT_OF_RANGE,
	EXC_SENSITIVITY_OUT_OF_RANGE,
	EXC_SCROLL_SENSITIVITY_OUT_OF_RANGE,
	EXC_LIGHT_INDEX_OUT_OF_RANGE,
	EXC_WRONG_LIGHT_INGREDIENT,
	EXC_WRONG_COLOR_INDEX,
	EXC_WRONG_ATTENUATION_TYPE,
	EXC_WRONG_ATTENUATION_MODEL,
	EXC_WRONG_LIGHT_TYPE,
	EXC_WRONG_CUTOFF_RANGE,
	EXC_WRONG_LIGHT_DIRECTION
}MyException;
//处理函数
void HandleException(MyException exc)
{

}
